### ISSUE TITLE
Introduce basic stats page

### ISSUE THREAD

**Issue by jayqui** [jayqui/amharic_letters_flashcards#13]
### User Story

As a user, I would like there to be a stats screen so that I can track my progress regarding how well I'm doing at memorizing the fidels of Amharic.

### Requirements

* Add a stats screen
* Retrieve some data to display on the stats screen
  * The stats data does not (at this time) need to come from a server, so no HTTP requests required to obtain the stats. Rather, the data storage can be local to the user's device
  * Note that elsewhere, the app is using [`AsyncStorage`](https://reactnative.dev/docs/asyncstorage), but this package has reached end-of-life, so for this stats page we should switch to a more modern solution. 
* Display the below-described content on it
  * For the purposes of this ticket, you can be using sample data. The task of _storing_ the data as one goes through the flashcards is for a separate ticket, https://github.com/jayqui/amharic_letters_flashcards/issues/12.

#### What to display

All we care about for the initial go-round at this is displaying the user's Weakest 5 Fidels (weakest first) and Strongest 5 Fidels (strongest first). For example, supposing user had the following collection of guesses

```js
{
  'ር': { correct: 0, attempted: 5 },
  'ም': { correct: 0, attempted: 3 },
  'ሆ': { correct: 0, attempted: 5 },
  'ሉ': { correct: 0, attempted: 4 },
  'ሂ': { correct: 0, attempted: 5 },
  'ቸ': { correct: 0, attempted: 5 },
}
```

we would then want the stats page's Weakest 5 Fidels section to display the weakest five with weakest first, like this:
```
ቸ: 0% (0 of 5),
ሂ: 20% (1 of 5),
ሉ: 50% (2 of 4),
ሆ: 60% (3 of 5),
ም: 66.7% (2 of 3)
```

### TODO list:

- [x] add basic stats page
- [x] add to main page navigation
- [ ] Adjust README
  - [x] re. how to run tests
  - [ ] re. `asdf`
- [x] Find an alternative to [`AsyncStorage`](https://reactnative.dev/docs/asyncstorage) — [looks like](https://reactnative.directory/?search=storage) [`@react-native-async-storage/async-storage`](https://github.com/react-native-async-storage/async-storage/tree/main/packages/default-storage) is by far the favorite
- [x] Code out (and test) the logic that calculates percentage, sorts, and takes top and bottom 5.
- [x] allow dynamic selection of top N fidels
- [x] make it a lil bit prettier

More relevant to https://github.com/jayqui/amharic_letters_flashcards/issues/12
- [ ] ~~Actually retrieve from the storage rather than from the hard-coded data structure~~
- [ ] ~~Make Clear Stats button work~~

### Acceptance Criteria
- Implementation of the above requirements
- Passing tests (do I as I say, not as I do . . .)
